@startuml example
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another request
Alice <-- Bob: Another response

Alice -> Bob: 日本語のアクション
Bob --> Alice: 日本語の応答
@enduml