vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}
network: {
  cell tower: {
    satellites: {
      shape: stored_data
      style.multiple: true
    }

    transmitter

    satellites -> transmitter: 送信
    satellites -> transmitter: 送信
    satellites -> transmitter: 送信
  }

  online portal: {
    ui: {shape: hexagon}
  }

  data processor: {
    storage: {
      shape: cylinder
      style.multiple: true
    }
  }

  cell tower.transmitter -> data processor.storage: 通話記録
}

user: {
  shape: person
  width: 130
}

user -> network.cell tower: 通話する
user -> network.online portal.ui: アクセス {
  style.stroke-dash: 3
}

api server -> network.online portal.ui: 表示
api server -> logs: 保存
logs: {shape: page; style.multiple: true}

network.data processor -> api server